import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { userService } from '../services'
import Navbar from '../components/Navbar'



const inter = Inter({ subsets: ['latin'] })
function logout() {
  userService.logout();
}


export default function Home() {
  return (
    <>
      <Head>
        <title>Task Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet"
  href="https://fonts.googleapis.com/css?family=Roboto"></link>
      </Head>
      <Navbar/>
      <h1>
      Hola {userService.userValue?.firstName}!
      </h1>
    
     
    </>
  )
}
